name = "wyckoff-pro"
compatibility_date = "2024-09-23"
pages_build_output_dir = "dist"

[vars]
VITE_SUPABASE_URL = "https://oijewqsmjmqbgcsvfkbf.supabase.co"
VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9pamV3cXNtam1xYmdjc3Zma2JmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc2NDM5MzUsImV4cCI6MjA5MzIxOTkzNX0.aV7ivfmNXEWsFw0CRYQQD2Rea7d-IpVIiE_QvTqhmrY"
